### PR TITLE
Giga preprocessing

### PR DESCRIPTION
**Pull request by ltetrel**
giga processing doc
qc to finish when it will be working

### CODE REVIEW

**Comment by lunebellec** [comment]
LGTM I have made a couple comments. I suggest to split the part on qc and turn it into a separate PR that we will merge later.

**Comment by ltetrel** [comment]
Seems reasonnable, I will just remove qc from this branch/commits then

**Comment by ltetrel** [comment]
Hmm actually it will create a mess in the git history if I remove the QC file from this PR.
So I will keep the file here, create a new branch for qc, commit on this new branch and make another PR (when QC will work, usable/shareable and doc is finished.)

**Comment by ltetrel** [comment]
@arnaudbore comme on en a parlé pendant notre meeting hier avec Basile, tu peux me donner les droits admins sur ce repo?

**Comment by lunebellec** [comment]
LGTM - merging. 

Also @ltetrel I've added you as maintainer.

**Pull request merged**
