### PR TITLE
start of adding welcome guide to lab website

### LINKED ISSUE #33: Formally add in the draft from the welcome_simexp channel
The doc is reasonably mature for the postdoc section.

For master and phd student, we need contributors.

I am happy to review this PR if anyone wants to take on it.

### PR DESCRIPTION
**Pull request by clarkenj**
Adding welcome guide for new lab members, such as visa and insurance processes.

Closes #33

### CODE REVIEW

**Comment by clarkenj** [comment]
@htwangtw

**Comment by clarkenj** [comment]
@htwangtw this is ready for your review. A few things I wasn't sure about:

- Do we want the link to the lab expertise sheet public? I have not included it for now.
- I have not added the info on group health insurance for now. I wasn't sure if it's up to date and/or if we want it public. But I can add it if you think so.
- I haven't added the info about conference expenses, what do you think?

**Review by htwangtw — COMMENTED** [review]
Content wise, LGTM! 
Make sure this is also referenced in the `index.rst`: 
https://github.com/SIMEXP/lab-documentation/blob/master/source/index.rst

**Comment by htwangtw** [comment]
> @htwangtw this is ready for your review. A few things I wasn't sure about:
> 
>     * Do we want the link to the lab expertise sheet public? I have not included it for now.
> 
>     * I have not added the info on group health insurance for now. I wasn't sure if it's up to date and/or if we want it public. But I can add it if you think so.
> 
>     * I haven't added the info about conference expenses, what do you think?

All these decisions are reasonable :+1:

**Review by htwangtw — APPROVED** [review]
LGTM!

**Comment by clarkenj** [comment]
Does Pierre need to review? I don't have ability to merge

**Comment by htwangtw** [comment]
I can merge it :)

**Pull request merged**
